
# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments
# Clean and don't fail
install:
  - sudo apt-get --yes install snapd
  - sudo snap install hugo
  - rm -rf public || exit 0
# Build the website
script:
  - hugo --theme=casper

  # Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master